#!/usr/bin/env python3
"""
BadUSB payload preparation agent — semi-interactive, Ollama-assisted.

Role: prepare classified scripts (see classify_badusb.py) before the user
copies them onto the Flipper Zero's SD card themselves (into badusb/). This
script never touches the SD card directly.

For each script:
  1. Deterministic (regex) detection of fields to customize — Discord
     webhook, Telegram bot/chat, attacker IP/port, email, bracket
     placeholders ([person], [text]...), API key. See FIELD_SPECS.
  2. If regex finds nothing, an optional fallback asks an Ollama model
     (tool-calling, never blindly-parsed free text — same philosophy as
     Bad_USB_Classifier/ollama_agent.py) whether it spots a field to
     configure. Any value returned by the model is re-verified verbatim in
     the file before being used: no blind replacement.
  3. Scripts with no detected field are copied as-is (no action needed —
     "plug and play").
  4. For scripts with detected fields, the user is asked once per field
     type (global value reused) or file by file depending on their choice
     — see collect_field_values().

See SETUP_METHODS.md (generated by --write-methods-doc) for the method used
per classification theme.
"""
from __future__ import annotations

import argparse
import logging
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from Bad_USB_Classifier.ollama_agent import (
    DEFAULT_MODEL,
    OllamaUnavailable,
    chat_with_tools,
)

logger = logging.getLogger(__name__)

DUCKY_EXTENSIONS = {".txt", ".duck", ".ds"}
SKIP_FILENAMES = {"readme.md", "license", "license.md", "classification.log"}


# ─── Method per theme (documentation + detection bias) ──────────────────────
# "needs" lists the FIELD_SPECS keys most often expected for this theme —
# only used for documentation/prioritization; regex detection runs on ALL
# files regardless of theme anyway.

THEME_METHODS: dict[str, dict] = {
    "exfiltration": {
        "needs": ["discord_webhook", "telegram_bot_token", "telegram_chat_id"],
        "note": "Sends collected data to an external service: almost always needs a destination (Discord webhook or Telegram bot).",
    },
    "credentials": {
        "needs": ["discord_webhook"],
        "note": "Steals/exfiltrates credentials — needs a destination to receive the results.",
    },
    "PassVault": {
        "needs": ["discord_webhook"],
        "note": "Exfiltration variant targeting password managers/browsers.",
    },
    "Mimikatz": {
        "needs": [],
        "note": "Local execution (local credential dump) — usually plug & play, still worth checking for an exfiltration destination.",
    },
    "Telegram": {
        "needs": ["telegram_bot_token", "telegram_chat_id"],
        "note": "Uses the Telegram API — needs a bot token + chat id.",
    },
    "web2Discord": {
        "needs": ["discord_webhook"],
        "note": "Web exfiltration -> Discord.",
    },
    "ReverseShell": {
        "needs": ["attacker_ip", "attacker_port"],
        "note": "Opens a shell back to the attacker — needs a listening IP + port.",
    },
    "remote_access": {
        "needs": ["attacker_ip", "attacker_port"],
        "note": "Remote access — often plug & play (e.g. reboot), sometimes IP/port if it's a reverse shell.",
    },
    "execution": {
        "needs": ["attacker_ip", "attacker_port"],
        "note": "Generic execution — varies, depends on the payload (some download a third-party script with no configuration).",
    },
    "phishing": {
        "needs": ["discord_webhook", "generic_url"],
        "note": "Phishing pages/links or input exfiltration — check URL/webhook.",
    },
    "iMessageExfil": {
        "needs": ["bracket_placeholder"],
        "note": "Targets a specific contact/text — replace [person]/[text] with real values before use.",
    },
    "CartmanSong": {"needs": [], "note": "Audio/visual prank — plug & play."},
    "prank": {
        "needs": [],
        "note": "Pranks with no exfiltration — plug & play in the vast majority of cases.",
    },
    "quackberry": {
        "needs": [],
        "note": "Explicitly documented by the authors as plug & play.",
    },
    "destructive": {
        "needs": [],
        "note": "Local destructive actions — generally no network destination.",
    },
    "ransom": {
        "needs": [],
        "note": "Ransomware simulations — local, no real C2 in these samples.",
    },
    "recon": {
        "needs": ["generic_url"],
        "note": "Info gathering — some scraping scripts have a target URL to adapt.",
    },
    "incident_response": {
        "needs": [],
        "note": "Defensive scripts (triage/forensics) — plug & play, no exfiltration expected.",
    },
    "mobile": {"needs": [], "note": "Targets Android/iOS — generally plug & play."},
    "general": {
        "needs": ["discord_webhook", "attacker_ip", "generic_url"],
        "note": "Catch-all — behavior varies, let generic detection decide.",
    },
    "unassigned": {
        "needs": [],
        "note": "Not categorized by the classifier — worth a manual read, auto-detection may be incomplete.",
    },
}


# ─── Deterministic detection of fields to customize ──────────────────────────


@dataclass
class FieldSpec:
    key: str
    label: str
    example: str
    pattern: re.Pattern
    # group(1) of the pattern = the exact substring to replace in the file


FIELD_SPECS: list[FieldSpec] = [
    FieldSpec(
        key="discord_webhook",
        label="Discord webhook URL",
        example="DISCORD_HOOK_URL",
        pattern=re.compile(r'(?i)\$?\bwebhook(?:_?url)?\b\s*=\s*["\']([^"\']*)["\']'),
    ),
    FieldSpec(
        key="telegram_bot_token",
        label="Telegram bot token",
        example="123456789:AAExampleTokenExampleTokenExample",
        pattern=re.compile(r'(?i)\$?\bbot_?token\b\s*=\s*["\']([^"\']*)["\']'),
    ),
    FieldSpec(
        key="telegram_chat_id",
        label="Telegram chat ID",
        example="123456789",
        pattern=re.compile(r'(?i)\$?\bchat_?id\b\s*=\s*["\']([^"\']*)["\']'),
    ),
    FieldSpec(
        key="attacker_ip",
        label="Attacker IP (LHOST)",
        example="192.168.1.42",
        pattern=re.compile(
            r"\b(LHOST|ATTACKER[_-]?IP|YOUR[_-]?IP|IP[_-]?ADDRESS)\b"
            r'(?:\s*=\s*["\']?([^"\'\s\n]*)["\']?)?'
        ),
    ),
    FieldSpec(
        key="attacker_port",
        label="Attacker listening port (LPORT)",
        example="4444",
        pattern=re.compile(r'\b(LPORT|ATTACKER[_-]?PORT)\b\s*=?\s*["\']?(\d*)["\']?'),
    ),
    FieldSpec(
        key="email",
        label="Email address",
        example="you@example.com",
        pattern=re.compile(
            r'(?i)\$?\b(?:your_?email|email)\b\s*=\s*["\']([^"\']*)["\']'
        ),
    ),
    FieldSpec(
        key="generic_url",
        label="Target URL",
        example="https://your-site-or-target.example",
        pattern=re.compile(r'(https?://(?:www\.)?example\.com[^\s"\']*)'),
    ),
    FieldSpec(
        key="bracket_placeholder",
        label="Value to replace (bracket placeholder)",
        example="(depends on the script — name, message, etc.)",
        pattern=re.compile(r"(\[[a-zA-Z_][a-zA-Z0-9_ ]{1,30}\])"),
    ),
    FieldSpec(
        key="api_key",
        label="API key",
        example="sk-...",
        pattern=re.compile(r'(?i)\$?\bapi_?key\b\s*=\s*["\']([^"\']*)["\']'),
    ),
]

# bracket_placeholder is the pattern most prone to false positives
# (PowerShell type casts like [Math]/[int], ini sections [Unit]/[Service],
# fake prompts [sudo]...). We only keep brackets that follow the community
# placeholder convention: ALL_CAPS_WITH_UNDERSCORE (EVIL_SERVER_IP,
# LISTENER_IP_ADDRESS...) or a common keyword from the list below (based on
# the real inventory of classified payloads).
BRACKET_KNOWN_WORDS = {
    "person",
    "text",
    "name",
    "target",
    "message",
    "url",
    "ip",
    "contact",
    "email",
    "phone",
    "victim",
    "username",
    "password",
    "recipient",
    "subject",
    "body",
    "filename",
    "address",
    "port",
}
_ALL_CAPS_UNDERSCORE = re.compile(r"^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$")


def _is_probable_placeholder(bracket_content: str) -> bool:
    word = bracket_content.strip()
    if _ALL_CAPS_UNDERSCORE.match(word):
        return True
    return word.lower() in BRACKET_KNOWN_WORDS


@dataclass
class FieldMatch:
    spec: FieldSpec
    line_no: int
    raw_line: str
    placeholder: str  # exact substring to replace, may be empty


def scan_file(content: str) -> list[FieldMatch]:
    matches: list[FieldMatch] = []
    seen_placeholders: set[tuple[str, str]] = set()
    lines = content.splitlines()

    for spec in FIELD_SPECS:
        for m in spec.pattern.finditer(content):
            placeholder = (
                next((g for g in reversed(m.groups()) if g is not None), "")
                if m.groups()
                else ""
            )
            if spec.key == "bracket_placeholder" and not _is_probable_placeholder(
                placeholder.strip("[]")
            ):
                continue
            key = (spec.key, placeholder)
            if key in seen_placeholders:
                continue
            seen_placeholders.add(key)
            line_no = content.count("\n", 0, m.start()) + 1
            raw_line = (
                lines[line_no - 1] if 0 <= line_no - 1 < len(lines) else m.group(0)
            )
            matches.append(
                FieldMatch(
                    spec=spec,
                    line_no=line_no,
                    raw_line=raw_line.strip(),
                    placeholder=placeholder,
                )
            )

    return matches


def is_valid_ducky(content: str) -> bool:
    keywords = ("STRING", "DELAY", "ENTER", "REM", "GUI", "ALT", "CTRL", "SHIFT")
    return any(
        line.lstrip().upper().startswith(keywords) for line in content.splitlines()
    )


# ─── Ollama fallback for files with no regex match ──────────────────────────

REPORT_TOOL_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "report_fields_needed",
            "description": "Reports the fields the user needs to customize in this script before use.",
            "parameters": {
                "type": "object",
                "properties": {
                    "fields": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "label": {
                                    "type": "string",
                                    "description": "What the value represents (e.g. 'target IP address')",
                                },
                                "exact_substring": {
                                    "type": "string",
                                    "description": "The EXACT substring present in the script to replace (copy-paste verbatim).",
                                },
                            },
                            "required": ["label", "exact_substring"],
                        },
                    },
                    "plug_and_play": {
                        "type": "boolean",
                        "description": "true if the script needs no configuration at all.",
                    },
                },
                "required": ["plug_and_play"],
            },
        },
    }
]


def ollama_fallback_scan(content: str, filename: str, model: str) -> list[FieldMatch]:
    """Last resort for files where regex found nothing. Any substring
    suggested by the model is re-verified verbatim in the file before being
    accepted — the model never modifies anything directly, it only
    suggests (structured tool call)."""
    found: list[FieldMatch] = []

    def on_tool_call(name: str, args: dict) -> str:
        if name != "report_fields_needed":
            return "Unknown tool."
        for f in args.get("fields", []):
            substring = (f.get("exact_substring") or "").strip()
            label = f.get("label") or "Value to customize"
            if substring and substring in content:
                line_no = content.count("\n", 0, content.index(substring)) + 1
                spec = FieldSpec(
                    key="ollama_suggested",
                    label=label,
                    example="",
                    pattern=re.compile(re.escape(substring)),
                )
                found.append(
                    FieldMatch(
                        spec=spec,
                        line_no=line_no,
                        raw_line=substring,
                        placeholder=substring,
                    )
                )
            else:
                logger.debug(
                    "Ignoring Ollama suggestion (not found verbatim): %r", substring
                )
        return f"{len(found)} field(s) kept."

    system_prompt = (
        "You're analyzing a Ducky Script (BadUSB payload) to spot whether the user "
        "needs to customize a value before using it (IP, email, URL, name, "
        "token, etc.). Reply ONLY via the report_fields_needed tool call. "
        "Don't invent anything: exact_substring must be copied verbatim from the script."
    )
    try:
        chat_with_tools(
            model,
            system_prompt,
            f"File: {filename}\n\n{content[:4000]}",
            tools=REPORT_TOOL_SCHEMA,
            on_tool_call=on_tool_call,
        )
    except OllamaUnavailable as e:
        logger.warning("Ollama unavailable for %s: %s", filename, e)
    except Exception as e:  # noqa: BLE001 - an AI failure must never block the run
        logger.warning("Ollama analysis failed for %s: %s", filename, e)
    return found


# ─── Interactive value collection ────────────────────────────────────────────


@dataclass
class SetupPlan:
    ready: list[Path] = field(default_factory=list)  # no configuration needed
    to_configure: dict[Path, list[FieldMatch]] = field(default_factory=dict)
    skipped: list[Path] = field(default_factory=list)


def analyze_tree(root: Path, use_ollama: bool, model: str) -> SetupPlan:
    plan = SetupPlan()
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.name.lower() in SKIP_FILENAMES:
            continue
        if path.suffix.lower() not in DUCKY_EXTENSIONS:
            plan.skipped.append(path)
            continue
        content = path.read_text(encoding="utf-8", errors="ignore")
        if not content.strip() or not is_valid_ducky(content):
            plan.skipped.append(path)
            continue

        matches = scan_file(content)
        if not matches and use_ollama:
            matches = ollama_fallback_scan(content, path.name, model)

        if not matches:
            plan.ready.append(path)
        else:
            plan.to_configure[path] = matches
    return plan


def print_summary(plan: SetupPlan) -> None:
    print("\n=== Analysis summary ===")
    print(f"  Ready to use (no config needed)   : {len(plan.ready)}")
    print(f"  Need configuration                 : {len(plan.to_configure)}")
    print(f"  Skipped (not BadUSB scripts)       : {len(plan.skipped)}")

    per_field: dict[str, int] = {}
    for matches in plan.to_configure.values():
        for m in matches:
            per_field[m.spec.key] = per_field.get(m.spec.key, 0) + 1
    if per_field:
        print("\n  Breakdown by field type:")
        for key, count in sorted(per_field.items(), key=lambda kv: -kv[1]):
            print(f"    - {key:<22} {count} file(s)")


# ─── Discord setup from scratch (freshly created account) ───────────────────
# Covers the whole chain: account -> server -> channel -> webhook. Triggered
# when the user says they don't have a webhook ready yet.

DISCORD_WEBHOOK_GUIDE = """
    Don't have a Discord webhook yet? Here's how to get one starting from a
    freshly created account:

      1. Account   : go to https://discord.com and create an account (or
                      sign in if you already have one).
      2. Server    : click the "+" at the bottom of the left server bar
                      -> "Create a server" -> "For me and my friends"
                      (any name, e.g. "BadUSB-Tests"). A private server is
                      enough, no need to make it public.
      3. Channel   : a default text channel exists (#general) — you can
                      use it as-is, or create a dedicated one
                      (right-click the category -> Create Channel).
      4. Webhook   : click the gear icon next to the channel
                      (Channel Settings) -> Integrations -> Webhooks
                      -> "New Webhook".
      5. Retrieval : give it a name, check the destination channel,
                      then click "Copy Webhook URL".

    The copied URL looks like:
      DISCORD_HOOK_URL
"""

DISCORD_WEBHOOK_RE = re.compile(
    r"^https://(?:canary\.|ptb\.)?discord(?:app)?\.com/api/webhooks/\d+/[\w-]+/?$"
)


def _ask_discord_webhook_value(prompt_text: str) -> str:
    """Asks for a Discord webhook URL, offers the creation guide if the
    user doesn't have one yet, and validates the format before accepting it.
    """
    ready = (
        input("    Do you already have a Discord webhook ready? [Y/n] ").strip().lower()
    )
    if ready == "n":
        print(DISCORD_WEBHOOK_GUIDE)
        input("    Press Enter once the webhook is created and its URL copied...")

    while True:
        val = input(prompt_text).strip()
        if not val:
            return ""
        if DISCORD_WEBHOOK_RE.match(val):
            return val
        print(
            "    ! This doesn't look like a valid Discord webhook URL "
            "(expected: https://discord.com/api/webhooks/<id>/<token>)."
        )
        if input("    Try again? [Y/n] ").strip().lower() == "n":
            return ""


def collect_field_values(plan: SetupPlan) -> dict[str, dict[Path, str]]:
    """For each field type encountered, asks the user for a global value
    (reused everywhere) or on a case-by-case basis. Returns
    {field_key: {file_path: value}}.
    """
    values: dict[str, dict[Path, str]] = {}

    fields_by_key: dict[str, list[tuple[Path, FieldMatch]]] = {}
    for path, matches in plan.to_configure.items():
        for m in matches:
            fields_by_key.setdefault(m.spec.key, []).append((path, m))

    for key, occurrences in fields_by_key.items():
        spec = occurrences[0][1].spec
        print(f"\n--- {spec.label} ({len(occurrences)} file(s)) ---")
        if spec.example:
            print(f"    Example: {spec.example}")
        mode = (
            input(
                "    [g] single value for all these files / [f] case by case / [s] skip this field: "
            )
            .strip()
            .lower()
        )

        values[key] = {}
        if mode == "s":
            continue
        if mode == "g":
            if key == "discord_webhook":
                val = _ask_discord_webhook_value(f"    Value for '{spec.label}': ")
            else:
                val = input(f"    Value for '{spec.label}': ").strip()
            for path, _m in occurrences:
                values[key][path] = val
        else:
            for path, m in occurrences:
                print(f"      {path.name} — line {m.line_no}: {m.raw_line[:100]}")
                prompt = f"      Value for '{spec.label}' (Enter to skip): "
                val = (
                    _ask_discord_webhook_value(prompt)
                    if key == "discord_webhook"
                    else input(prompt).strip()
                )
                if val:
                    values[key][path] = val

    return values


# ─── Applying values + copying to ready_to_flash/ ────────────────────────────
#
# root == output_root is a valid mode ("in-place enrichment"): used by
# badusb_pipeline.py to finalize the folder already produced by the
# classifier, without creating a 3rd copy (raw -> classified ->
# ready_to_flash). root != output_root reproduces this module's historical
# behavior (copying from an already-classified folder to a separate
# ready_to_flash folder).


def apply_and_copy(
    root: Path, output_root: Path, plan: SetupPlan, values: dict[str, dict[Path, str]]
) -> list[str]:
    report_lines: list[str] = ["# Payload preparation report\n"]
    in_place = output_root.resolve() == root.resolve()

    for path in plan.ready:
        if not in_place:
            dest = output_root / path.relative_to(root)
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, dest)
        report_lines.append(f"- OK  (plug & play)     {path.relative_to(root)}")

    for path, matches in plan.to_configure.items():
        content = path.read_text(encoding="utf-8", errors="ignore")
        applied: list[str] = []
        pending: list[str] = []

        for m in matches:
            new_val = values.get(m.spec.key, {}).get(path)
            if not new_val:
                pending.append(m.spec.label)
                continue
            if m.placeholder:
                content = content.replace(m.placeholder, new_val)
            else:
                content = content.replace(m.raw_line, f"{m.raw_line}{new_val}")
            applied.append(f"{m.spec.label} -> {new_val}")

        dest = output_root / path.relative_to(root)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

        rel = path.relative_to(root)
        if pending:
            report_lines.append(
                f"- REVIEW  {rel}  (not filled in: {', '.join(pending)})"
            )
        else:
            report_lines.append(f"- CONFIG  {rel}  ({'; '.join(applied)})")

    return report_lines


def write_methods_doc(dest: Path) -> None:
    lines = [
        "# Configuration method by theme\n",
        "Generated by payload_setup_agent.py — details what each payload",
        "category expects before copying onto the Flipper Zero.\n",
    ]
    for theme, info in THEME_METHODS.items():
        needs = ", ".join(info["needs"]) if info["needs"] else "none (plug & play)"
        lines.append(f"## {theme}\n\n- Expected fields: {needs}\n- {info['note']}\n")
    dest.write_text("\n".join(lines), encoding="utf-8")
    print(f"Methods written to {dest}")


# ─── CLI ──────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepares BadUSB payloads before copying them onto the Flipper Zero."
    )
    parser.add_argument(
        "directory",
        nargs="?",
        help="Classified folder to analyze (e.g. ~/Desktop/classified_badusb)",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output folder (default: <directory>_ready_to_flash next to it)",
    )
    parser.add_argument(
        "--model",
        default="qwen2.5-1.5b-heretic:latest",
        help="Ollama model for the fallback (tool-calling required)",
    )
    parser.add_argument(
        "--no-ollama",
        action="store_true",
        help="Disable the AI fallback, regex only",
    )
    parser.add_argument(
        "--write-methods-doc", metavar="FILE", help="Write SETUP_METHODS.md and exit"
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if args.write_methods_doc:
        write_methods_doc(Path(args.write_methods_doc))
        return 0

    if not args.directory:
        parser.print_help()
        return 1

    root = Path(args.directory).expanduser().resolve()
    if not root.is_dir():
        print(f"Error: {root} is not a valid directory.")
        return 1

    output_root = (
        Path(args.output).expanduser().resolve()
        if args.output
        else root.parent / f"{root.name}_ready_to_flash"
    )

    print(f"Analyzing {root} ...")
    plan = analyze_tree(root, use_ollama=not args.no_ollama, model=args.model)
    print_summary(plan)

    if not plan.to_configure:
        print("\nNo files need configuration — copying directly.")
    else:
        proceed = input("\nContinue and configure these files? [Y/n] ").strip().lower()
        if proceed == "n":
            print("Cancelled.")
            return 0

    values = collect_field_values(plan) if plan.to_configure else {}

    if output_root.exists():
        confirm = (
            input(f"{output_root} already exists, overwrite it? [y/N] ").strip().lower()
        )
        if confirm != "y":
            print("Cancelled.")
            return 0
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True)

    report_lines = apply_and_copy(root, output_root, plan, values)
    report_path = output_root / "setup_report.md"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")

    print(f"\nDone. Files ready in: {output_root}")
    print(f"Detailed report: {report_path}")
    print(
        "\nAll that's left is to manually copy this folder into badusb/ on the Flipper Zero's SD card."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
